package pin.jarbox.dat;

public enum DataNature {
  BOOL, BIT, BYTE, TINY, SMALL, INT, LONG, SERIAL, SERIAL_LONG, FLOAT, REAL, DOUBLE, NUMERIC, CHAR, CHARS, PASS, DATE, TIME, DATE_TIME, TIMESTAMP, TEXT, BYTES
}
